# @package _global_
defaults:
  - base_submitit
  - override /hydra/launcher: submitit_slurm

is_nlp_cluster: True

hydra:
  launcher:
    # slurm partition to use on the cluster
    partition: sphinx
    comment: null
    constraint: null # 12G,11G,24G,pascal,ampere,maxwell,turing,volta # TODO test if works if not will have to use gres
    exclude: sphinx3
    array_parallelism: 12
    mem_gb: 120
    cpus_per_task: 32

    max_num_timeout: 10 # allow resume from checkpointing
    gpus_per_node: 1
    additional_parameters:
      #nodelist:  #
      account: nlp