# @package _global_
predictor:
  is_sklearn: False

trainer:
  max_epochs:  300 # 15 # Dev
  log_every_n_steps: 200
  flush_logs_every_n_steps: 200
  enable_checkpointing: True

  # ENGINEERING / SPEED #
  gpus: 1
  num_nodes: 1  # number gpu nodes
  precision: 16 # use 16 bit for speed # TODO use "b16" once it is not experiemntal (maybe lightning 1.6)

checkpoint:
  kwargs:
    dirpath: ${paths.checkpoint}
    monitor: train/${component}/loss
    mode: "min"
    verbose: true
    save_last: True
    save_top_k: 1
    save_weights_only: false
