# @package _global_
predictor:
  is_sklearn: False
  architecture: ${predictor.arch_kwargs.architecture} # used for naming
  name: torch_${predictor.architecture}_lr${predictor.opt_kwargs.lr}_wdec${predictor.opt_kwargs.weight_decay}_ep${trainer.max_epochs}_bs${data.kwargs.batch_size}
  metrics: [ accuracy_score,log_loss ]
  arch_kwargs:
    architecture: ???
  opt_kwargs:
    lr: 0.3
    weight_decay: 1e-6
    momentum: 0 # should really be usign 0.9 historical reasons 0.0

trainer:
  max_epochs:  100
  log_every_n_steps: 200
  flush_logs_every_n_steps: 200
  enable_checkpointing: True

  # ENGINEERING / SPEED #
  gpus: 1
  num_nodes: 1  # number gpu nodes
  precision: 16 # use 16 bit for speed # TODO use "b16" once it is not experiemntal (maybe lightning 1.6)

checkpoint:
  kwargs:
    dirpath: ${paths.checkpoint}
    monitor: null #train/${component}/loss
    mode: "min"
    every_n_epochs: 1 # don't monitor loss just save all
    verbose: true
    save_last: True
    save_top_k: 1
    save_weights_only: false
