defaults:
  - base_sklearn

name: sk_logistic
metrics: [accuracy_score,log_loss]
model:
  _target_: sklearn.linear_model.LogisticRegression
  penalty: "l2"
  C: 1 #smaller regularizes more (should tune it)
  random_state: ${seed}
  solver: "lbfgs" # should probably use "saga" for large datasets (but might need to normalize)
  n_jobs: -1  # won't work with sklearnex
  max_iter: 1000
  verbose: 1
  warm_start: true # when hyperparameter tuning this should make things much quicker