defaults:
  - torch_linear_hypopt

name: torch_linear_hypopt_test

hypopt:
  to_eval_first:
    # those are standard linear eval hparam => tuning should consider those
    basic_sgd:
      lr: 0.3
      optim: sgd
      scheduler: warmcosine
      weight_decay: 1e-6
      batch_size: 11
      is_batchnorm: false
    basic_adam:
      lr: 0.1 # 1e-3 adam
      optim: adam
      scheduler: multistep
      weight_decay: 1e-6
      batch_size: 9
      is_batchnorm: false