defaults:
  - pytorch

# using param like https://github.com/facebookresearch/barlowtwins/blob/main/evaluate.py
name: torch_logistic
metrics: [accuracy_score,log_loss]
arch_kwargs:
  architecture: linear
  is_normalize: False
opt_kwargs:
  lr: 0.3
  weight_decay: 1e-6 # only diff is that you don't want to
  momentum: 0.9